#################################################
# config.yaml
# 01 Aug 2013
# Said ÖZCAN									
# Instagram Printer
#################################################

accessToken: '209007001.32dc0e6.fa922df8ffbb4cba90529aab1a45e3d9'

searchHashtag: 'InstagramPrinter'

delayTime: 30.0

pageTitle: 'InstagramPrinter'

templateFileName: 'main.html'